### ISSUE TITLE
5.6.28 FPM 

### ISSUE THREAD

**Issue by ralfbecker** [iuscommunity-pkg/php56u#21]
Since Update to 5.6.28 FPM is not working anymore, reverting to 5.6.27 immediately fixes the Problem:
Nov 20 00:15:27 node9 docker[10113]: 2016/11/19 23:15:27 [error] 14#14: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 180355072 bytes exhausted (tried to allocate 4294966847 bytes) in /var/www/mserver/egroupware/managementserver/server

Locking at the numbers, it tries to allocate 4294966847 bytes = 4GB, which is obviously bigger then our memory_limit of 180MB.

As far as I can tell every php script triggers the error. Our Environment is Nginx 1.10.2 (under Ubuntu in Docker containers) with several PHP FPM under CentOS 7 also in containers. 

I don't think problem is related to the environment of our main EGroupware hosting farm, as starting FPM containers in previous version 5.6.27 immediately fixes the problem. 

I'll check if it problem also happens on simple CentOS 7 with Nginx and FPM on a single machine and report back here. 

I would recommend removing 5.6.28 FPM packages from the repo!

Ralf

**Comment by ralfbecker** [comment]
Tried it on a CentOS 7 test-box with Nginx/FPM and it does NOT show the above described behavior. Even switching from APCu to PHP memcache extension for cache and sessions works fine.

So it looks like an can not reproduce that problem (allocating 4GB) outside our hosting farm.

Looking at your changelog in RPM does not suggest you did anything different compared to previous release 5.6.27. 

Any ideas?

**Comment by b-harper** [comment]
Hey @ralfbecker,

I have a gut feeling that this is not a packaging issue.  As you discovered, we did not make any changes to the RPMs besides changing the version.  Looking at the upstream [changelog][0],  nothing jumps out that would cause this issue.  

Looking at PHP's bug tracker, there are two bugs that could be related to your issue:

https://bugs.php.net/bug.php?id=73497
https://bugs.php.net/bug.php?id=73539

You might want to look at disabling modules in some test containers to help narrow down this issue. 

[0]:  http://php.net/ChangeLog-5.php#5.6.28

**Comment by ralfbecker** [comment]
Hi Ben,
that's exactly the bug, I could not reproduce it, as I only tried with a single memached server, not with 2 as in our production environment and as described in the bug-report.
Let's hope the report get some attention soon, otherwise we need to build a patched memcache extension ...
Ralf

**Comment by ralfbecker** [comment]
Locking at PECL memcache v. 3.0.8 released 2013 as beta, I doubt there will be a quick reaction, not to say a reaction at all.
Do you mind adding the patch the IUS package? I'm willing to test it.
Ralf

**Comment by b-harper** [comment]
It has been some time since the last memcache release.  That being said, I am hesitant to add a patch from some random user with no comments.  I'll keep an eye on that bug.

I am curious if the memcached pecl module is also effected.

**Comment by b-harper** [comment]
[PHP 5.6.29][0] has been released.  It is just a security release and there are [no changelog entires ][1] that show this issue has been addressed.  [PHP bug #73497][2] got an update, and someone is having the same issue with redis and multiple servers. 

[0]: https://php.net/archive/2016.php#id2016-12-08-2
[1]: https://secure.php.net/ChangeLog-5.php#5.6.29
[2]: https://bugs.php.net/bug.php?id=73497

**Comment by b-harper** [comment]
PHP 5.6.30 has been released  and is the [last planned release that contains regular bugfixes][0].  If this is an issue with PHP 5.6 itself and not module, it may not get fixed.  


[0]: http://php.net/archive/2017.php#id2017-01-19-3

**Comment by ralfbecker** [comment]
The issue is not resolved, but as far as I can tell it's not an issue of FPM in general, but memcache extension using some method from PHP, which has sightly changed. And seems noone cares about old memcache extension anymore.

I moved with our EGroupware hosting now to PHP 7.0 and new memcached extension, so the issue is kinda "solved" for me ;)

**Comment by b-harper** [comment]
Hey @ralfbecker,

Thanks for the feedback.  I would agree with your assessment of this issue.  I also think moving to PHP 7 is a good idea for many reasons.

Seeing that @ralfbecker feels this issue is closed, I am going close this issue.  If anyone feels we need to revisit this issue, we can open it back up.
